# Constants
BOARD_ROWS = 8
BOARD_COLS = 8

# Positions
ORIGIN = (0, 0)

# Colors
DARK_COLOR = (50, 85, 255)
LIGHT_COLOR = (200, 200, 200)

# Sizes
TILE_LENGTH = 50
TILE_SIZE = (TILE_LENGTH, TILE_LENGTH)

BOARD_WIDTH = (2 + BOARD_COLS) * TILE_LENGTH
BOARD_HEIGHT = (2 + BOARD_ROWS) * TILE_LENGTH
BOARD_SIZE = (BOARD_WIDTH, BOARD_HEIGHT)

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 550
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
